# Generated by Django 4.0.3 on 2022-05-04 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_collection_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headportrait',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y%m%d/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.comment')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
