# Generated by Django 4.0.3 on 2022-05-07 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_user_friend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
