# Generated by Django 3.2.13 on 2022-05-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_user_friend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(default='他貌似没什么想说的呢...', max_length=50),
        ),
    ]
